@extends('layouts.sekretaris')
@section('title', 'Isi Jurnal Guru')
@section('header', 'Isi Jurnal Guru')
@section('content')
<div class="page-heading"><h2>Isi Jurnal Atas Nama Guru</h2><p>Jurnal disimpan dengan guru pengampu dari jadwal yang dipilih dan langsung tersedia bagi staf piket.</p></div>
<div class="card" style="max-width:900px"><div class="notice" style="margin-bottom:20px">Pastikan pengisian sudah mendapatkan konfirmasi dari guru pengampu.</div>
<form method="POST" action="{{ route('sekretaris.isi-jurnal.store') }}">@csrf
<div class="form-grid"><div class="field full"><label>Jadwal guru</label><select name="id_jadwal" required><option value="">Pilih jadwal guru</option>@foreach($jadwals as $jadwal)<option value="{{ $jadwal->id_jadwal }}" @selected(old('id_jadwal') == $jadwal->id_jadwal)>{{ $jadwal->guru->nama_guru }} — {{ $jadwal->mapel->nama_mapel }} — {{ $jadwal->kelas->nama_kelas }} (Jam {{ $jadwal->jamMulai->jam_ke }}-{{ $jadwal->jamSelesai->jam_ke }})</option>@endforeach</select></div><div class="field"><label>Tanggal pembelajaran</label><input name="tanggal" type="date" value="{{ old('tanggal', now()->toDateString()) }}" required></div><div class="field"><label>Status guru</label><select name="status_guru" required><option value="Hadir" @selected(old('status_guru') === 'Hadir')>Hadir</option><option value="Izin" @selected(old('status_guru') === 'Izin')>Izin</option><option value="Sakit" @selected(old('status_guru') === 'Sakit')>Sakit</option><option value="Tanpa Keterangan" @selected(old('status_guru') === 'Tanpa Keterangan')>Tanpa Keterangan</option></select></div><div class="field full"><label>Materi pembelajaran</label><input name="materi" value="{{ old('materi') }}" placeholder="Contoh: Persamaan kuadrat dan penerapannya" required></div><div class="field"><label>Jumlah hadir</label><input name="jml_hadir" type="number" min="0" value="{{ old('jml_hadir') }}" required></div><div class="field"><label>Jumlah tidak hadir</label><input name="jml_tidak_hadir" type="number" min="0" value="{{ old('jml_tidak_hadir') }}" required></div><div class="field"><label>Ada tugas?</label><select name="ada_tugas" required><option value="Tidak" @selected(old('ada_tugas') === 'Tidak')>Tidak</option><option value="Ya" @selected(old('ada_tugas') === 'Ya')>Ya</option></select></div><div class="field"><label>Deskripsi tugas (jika ada)</label><input name="deskripsi_tugas" value="{{ old('deskripsi_tugas') }}" placeholder="Tugas untuk siswa"></div><div class="field full"><label>Catatan pembelajaran</label><textarea name="catatan_umum" placeholder="Ringkasan kegiatan atau catatan dari guru.">{{ old('catatan_umum') }}</textarea></div></div>
<div class="form-actions"><button class="button outline" type="reset">Bersihkan</button><button class="button" type="submit">Simpan Jurnal</button></div></form></div>
@endsection
