@extends('layouts.sekretaris')
@section('title', 'Validasi Jurnal')
@section('header', 'Validasi Jurnal')
@section('content')
<div class="page-heading"><h2>Validasi Jurnal Guru</h2><p>Jurnal yang disetujui akan otomatis tampil pada akun staf piket.</p></div>
<div class="card"><form class="filters" method="GET"><input class="input" name="search" value="{{ request('search') }}" placeholder="Cari guru atau kelas..."><select class="select" name="kelas_id"><option value="">Semua kelas</option>@foreach($kelases as $kelas)<option value="{{ $kelas->id_kelas }}" @selected(request('kelas_id') == $kelas->id_kelas)>{{ $kelas->nama_kelas }}</option>@endforeach</select><select class="select" name="status"><option value="">Semua status</option>@foreach(['Menunggu','Disetujui','Perlu Diperbaiki','Ditolak'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><input class="select" name="tanggal" type="date" value="{{ request('tanggal') }}"><button class="button outline">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Guru</th><th>Kelas / Jam</th><th>Materi</th><th>Kehadiran</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($jurnals as $jurnal)<tr><td><span class="teacher"><span class="teacher-dot">{{ strtoupper(substr($jurnal->guru->nama_guru ?? 'G', 0, 1)) }}</span>{{ $jurnal->guru->nama_guru ?? '-' }}</span></td><td>{{ $jurnal->kelas->nama_kelas ?? '-' }}<br><small>Jam ke-{{ $jurnal->jamMulai->jam_ke ?? '-' }} — {{ $jurnal->jamSelesai->jam_ke ?? '-' }}</small></td><td>{{ $jurnal->materi }}</td><td>{{ $jurnal->jml_hadir }} hadir / {{ $jurnal->jml_tidak_hadir }} tidak hadir</td><td>{{ $jurnal->tanggal?->format('d M Y') }}</td><td><span class="badge {{ $jurnal->status_validasi_guru === 'Disetujui' ? 'valid' : ($jurnal->status_validasi_guru === 'Menunggu' ? 'pending' : 'revision') }}">{{ $jurnal->status_validasi_guru }}</span></td><td>@if($jurnal->status_validasi_guru === 'Menunggu')<form method="POST" action="{{ route('sekretaris.validasi-jurnal.update', $jurnal) }}">@csrf @method('PATCH')<input type="hidden" name="status_validasi_guru" value="Disetujui"><button class="button">Setujui</button></form>@else<span style="color:#73809a;font-size:11px">{{ $jurnal->catatan_revisi ?: 'Sudah diproses' }}</span>@endif</td></tr>
@empty<tr><td colspan="7" style="text-align:center;color:#73809a;padding:25px">Belum ada jurnal yang sesuai.</td></tr>@endforelse
</tbody></table></div>
@if($jurnals->hasPages())<div style="margin-top:18px">{{ $jurnals->links() }}</div>@endif</div>
@endsection
